name: Create GitHub Environment Variable

on:
  push:
    branches:
      - master

jobs:
  create_github_env_variable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variable
      run: |
        echo -e "MY_VARIABLE=my_value" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
