name: Azure Resources

on:
  workflow_dispatch:

jobs:
  check-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Creating Release Notes        
        uses: actions/github-script@v6
        with:
          script: |       
            await github.request('PATCH /repos/{owner}/{repo}/actions/variables/{name}', {
              owner: 'DevOps-Renan',
              repo: 'devops_infrastructure_library',
              name: 'AZURE_RESOURCES_JSON',
              value: 'ola',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
              
