name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Creating Release Notes   
      #   shell: bash     
      #   run: |       
      #     echo "az_resources=$(curl -H "Content-Type: application/json" \
      #       -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEyNDEzNTAsIm5iZiI6MTY4MTI0MTM1MCwiZXhwIjoxNjgxMjQ2MTgwLCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBL1g5cWFrdGswSXJSd3BjUHJBOUg1NUlTZGp3bXM1MXBuYy9NdWRic2RENEJZZHMwM0J1dFErVHNCdkF3bWd0K1F1M2ZxRDZMVVJyZ3FNN0t4T1Z5MjhjMVB4bW1qbGNmTWMvc1JNZUw1bzA9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImFZb2lJWmpSRGs2R0NxM29ydzhMQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.UTcXFvywRn-1OMJymrpG_k_NqHzhwDA_teDdwShYd9GTwTBjRF1tnwI7mlKo_uKkNJmSBNLcpGE2nCLKwcUPQlKOqgqn1xJ7xAL2CQQmc2S-TIbta-OK5M9hqWFc_mAWsXuenMaZjDK6wlhSlFURWHPupbGNALvSpmR4HDdQpiJiz_kw2KphJyaeCmsjZObozCLO3r9vNhJMQOm2ElI9N7DJGc4bC8ohghEsvw4IKnIWbigdxOONRYFnWCkAE8ymcciyFXXCKCBeaRB_6wIjS5LkjechA9Xe0LAULxu0xyqzsD1rnbX7ic7TJOqsteZJpFkP4yYbk9M6ig3NBd0GAg" \
      #       https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01)" >> $GITHUB_ENV

      - name: Creating Release Notes 1
        shell: sh     
        run: |                
          import tempfile
          import requests
          import json

          with open("response.json", "r") as arquivo:
              json1 = arquivo.read()

          # Converte o objeto JSON em um dicionário Python
          data_a = json.loads(json1)

          # Acessa a chave "value" do dicionário e imprime seu valor
          array_a = data_a['value']

          url = "https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01"

          headers = {
              "Content-Type": "application/json",
              "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEzOTkyMzIsIm5iZiI6MTY4MTM5OTIzMiwiZXhwIjoxNjgxNDA0MDE3LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBS0V2Z1RYRjNXQ0tEMWUxV29uSGpnWHVpRWIxVWpkRitobldVd2U3QVJDRS90aGl2MXV5LzFTbkJHRnNVU1QvMm16bEU4WXZUdUZueHBhRXQ1Ti9vRi9aWk9LemFtNm1telAvU1o0UVZhM0E9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImNuNXJuMlBsNlVtMWhXZVZXMkJQQWciLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.MrmUEzQQsafZa3454T7uaHU4iq_vwGcyLoG3uVYSWgEXkMX2k_qKZPtYD4P61qbAl0ARM1vJa-CdNcj84oPC3hjAzx0R0xJcOz_dvbLBO7RdZPETBcSvHaeqm3yWINmM078MjgbCSYGdAKQx951jC7eMfLcVB0RxMB2DYCldY8uOMjSjiGs3FoVZD8rhdNtibIy53kaM1CV5W0LFceIWMhtLpei0ViDe5B6eOly47GpobF9xBa14itX1nw8KN5NB61Bzs-66AfniJU3XSEjHVtC6uIP7OXCA81psCGIlriYQ_g2CNTy5nfZeiuA5ixjVmb-fqXs9qpaxPhXM5MUssg"
          }

          response = requests.get(url, headers=headers)

          json2 = response.content

          # Converte o objeto JSON em um dicionário Python
          data_b = json.loads(json2)

          # Acessa a chave "value" do dicionário e imprime seu valor
          array_b = data_b['value']

          # Cria um arquivo temporário para o array A
          with tempfile.TemporaryFile(mode='w+t') as file_a:
              file_a.writelines([f"{item}\n" for item in array_a])
              file_a.seek(0)

              # Cria um arquivo temporário para o array B
              with tempfile.TemporaryFile(mode='w+t') as file_b:
                  file_b.writelines([f"{item}\n" for item in array_b])
                  file_b.seek(0)

                  # Lê o conteúdo dos arquivos temporários e converte em conjuntos
                  set_a = set(file_a.readlines())
                  set_b = set(file_b.readlines())

                  # Calcula a diferença entre os conjuntos
                  added = set_b - set_a
                  removed = set_a - set_b

                  if added or removed:
                      

                  # Imprime o resultado
                  if added:
                      print(f"Adicionado from A to B: {added}")
                  else if removed:
                      print(f"Removido from A to B: {removed}")
                  else:
                      print("Não ocorreu mudanças")
