name: Criar Variável de Ambiente
# on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Obter token de acesso
        run: |
          # Define as variáveis necessárias para obter o token de acesso
          CLIENT_ID=a4f94bee-c32f-483b-a7f0-8018569218fc
          CLIENT_SECRET=f8O8Q~nX8FaZtOvB1w_R2ZZWj0Iequk3W7NAFcLt
          TENANT_ID=818704fb-8ff3-4d28-9a05-f542c91abe46
          RESOURCE='https://management.azure.com/'
          # Obtém o token de acesso da API da Azure
          ACCESS_TOKEN=$(curl -X POST "https://login.microsoftonline.com/$TENANT_ID/oauth2/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=$CLIENT_ID" \
            -d "client_secret=$CLIENT_SECRET" \
            -d "resource=$RESOURCE" \
            | jq -r .access_token)

          # Define as variáveis necessárias para enviar a requisição
          API_URL='https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01'
          # Envia a solicitação para a API da Azure
          echo "x=$(curl -X GET $API_URL \
            -H "Authorization: Bearer $ACCESS_TOKEN")" >> $GITHUB_ENV

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Instalar módulos Python necessários
        run: |
          pip install requests

      - name: Executar script Python
        id: meu_script
        run: |
          python script.py
        env: 
          JSON: ${{ env.x }}

      - name: Mostrar resultado
        if: ${{ steps.meu_script.outputs.changed }} == "true"
        run: |
          git config user.email "renansampaio04@eyahoo.com.br"
          git config user.name "RenanSampaioRS"
          git add response.json
          git commit -m "Adicionando arquivo com resposta da requisição GET"
          git push origin master
