name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:

      - name: Creating Release Notes   
        shell: bash     
        run: |       
          echo "az_resources=$(curl -H "Content-Type: application/json" \
            -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEyMzU1MjksIm5iZiI6MTY4MTIzNTUyOSwiZXhwIjoxNjgxMjQwNTg2LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBbnBTVHhUUDBsQzBIc3hlZklXNlI2ZytNNTB4bS85MDZmMWFoWDl1Rjljdmp3ME1tTnArWjVUa0MrOWxPT0lJejdjTVBPOFhRR1RlU211ZTdNdSsvMDFaRUxOdXErcm1kbnRtMHZ0TDgwR0U9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImxwU2pJbEdSYUUtUUpYUDFwY3pUQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.pHMtWGE1jVc2WWaSclNCN4nr2F6KQPwqIg4cAQGk0U8-fBQWwJnJn3PcJZFeaHLDYhZ8VKCwRGLTQJTDSXwxVvgMhbVxUB3eu05yHA0CHSrJ5DqdYewG68sbgDr_DZQejArniEXCvqSnSz_L02r1ejJwM3sClN3Jx4eHGHHW-hnFuTu7PrDCQ5zMJYH2yEQcBRkuboTloK9NBB_RJJDk4hLdMCOs8ynpO6OXr1NByVursk2fsHShjVeDvsYiVlpL6M6sez45hXv6csQNF51YT8tMpK6_3uSziPTb7Jvm7z7L96sqyva9WjCi4GlDkwLPw4T6pyiiVEkuJYcOQu5eHg" \
            https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01)" >> $GITHUB_ENV

          json_str=$(echo "${{ env.az_resources }}" | jq -c '.')

          echo "$json_str"
  
      - name: Creating Release Notes        
        run: |       
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SECRET }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DevOps-Renan/devops_infrastructure_library/actions/variables/AZURE_RESOURCES_JSON \
            -d '{"name":"AZURE_RESOURCES_JSON","value":'ola'}'

