name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
    - name: Criação de Variável de Ambiente
      run: echo "NOME_DA_VARIAVEL=valor_da_variavel" >> $GITHUB_ENV
