name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Creating Release Notes   
      #   shell: bash     
      #   run: |       
      #     echo "az_resources=$(curl -H "Content-Type: application/json" \
      #       -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEyNDEzNTAsIm5iZiI6MTY4MTI0MTM1MCwiZXhwIjoxNjgxMjQ2MTgwLCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBL1g5cWFrdGswSXJSd3BjUHJBOUg1NUlTZGp3bXM1MXBuYy9NdWRic2RENEJZZHMwM0J1dFErVHNCdkF3bWd0K1F1M2ZxRDZMVVJyZ3FNN0t4T1Z5MjhjMVB4bW1qbGNmTWMvc1JNZUw1bzA9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImFZb2lJWmpSRGs2R0NxM29ydzhMQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.UTcXFvywRn-1OMJymrpG_k_NqHzhwDA_teDdwShYd9GTwTBjRF1tnwI7mlKo_uKkNJmSBNLcpGE2nCLKwcUPQlKOqgqn1xJ7xAL2CQQmc2S-TIbta-OK5M9hqWFc_mAWsXuenMaZjDK6wlhSlFURWHPupbGNALvSpmR4HDdQpiJiz_kw2KphJyaeCmsjZObozCLO3r9vNhJMQOm2ElI9N7DJGc4bC8ohghEsvw4IKnIWbigdxOONRYFnWCkAE8ymcciyFXXCKCBeaRB_6wIjS5LkjechA9Xe0LAULxu0xyqzsD1rnbX7ic7TJOqsteZJpFkP4yYbk9M6ig3NBd0GAg" \
      #       https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01)" >> $GITHUB_ENV

      - name: Creating Release Notes 1
        shell: bash     
        id: random-color-generator
        run: |                
          # json1=$(cat response.json)
          json1='{"value": [{"a": "x", "b": "y"}, {"c": "z"}]}'
          array1=$(echo $json1 | jq '.value')
          echo "array1=$array1" >> $GITHUB_ENV
          echo ${{ env.array1 }}
          
          # json2=$(curl -H "Content-Type: application/json" \
          #   -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEzODg2NTcsIm5iZiI6MTY4MTM4ODY1NywiZXhwIjoxNjgxMzkyOTU2LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBbEJZNUd2MUlEWWRKbEVLUHNvWVFqSmM3TkNOcDRzVXZOaTVVODE5MGxqWHBkamhjUXlhVW1xdG5aT1RIbVhJVkRkNC92bjczTzhIQWNJUi9HVWdGb29JUHlmTUoxaWdzVzJvTTBFODM0T3c9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Im5ERmhaVXNIOFVpUDNRZkNRRHNZQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.VvRYsmRZnJnUS7CEdIZTXZmls3YjivYq6B8ciAB-EvIh-NyVIqW3ul7nQ-wlQ7ekdks3JCgrTCW5HFbrx22sQhdSDY0SoPH9Ik4ApE4f8S7XytBc9YKlYDnR9rCPkp3exhhZ2TaMJBqTH5dM61wvFJl19gankeSQbsweJDpSWLl7NA02WUzslKbrXuz245nB2GiIdnmC4-kw8kNtoaMLIzUE2EpwvU9cxx7ornE3152c1biDlNZVpRbY-F_BPPnsf67HzFTLUoX-24e_cjgzbhY8jOJ7L0Kt65nDcuPJsoTqOa2OlN4-xp4VoaO6VnfG9gHBRnMDm-uiV0ewtdsf_g" \
          #   https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01)
          # array2=$(echo $json2 | jq '.value')
          # echo "array2=$array2" >> $GITHUB_ENV


      - name: Creating Release Notes 2 
        shell: bash     
        run: |                

          # Identifica as adições
          added=$(echo "${{ env.array2 }}" | jq --argjson array1 "${{ env.array1 }}" '. - ${{ env.array1 }}')

          # Identifica as deleções
          deleted=$(echo "${{ env.array1 }}" | jq --argjson array2 ${{ env.array2 }}" '. - ${{ env.array2 }}')

          # Verifica se houve adições ou deleções
          if [ "$added" != "[]" ] or [ "$deleted" != "[]" ]; then
            curl -o response.json -H "Content-Type: application/json" \
            -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzgxODcwNGZiLThmZjMtNGQyOC05YTA1LWY1NDJjOTFhYmU0Ni8iLCJpYXQiOjE2ODEzMjY1MTUsIm5iZiI6MTY4MTMyNjUxNSwiZXhwIjoxNjgxMzMxNDQwLCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBWndoeTRyaGt2VFhmbVZBbjJrU00vQ3FyTW1DNVZ1RjFLUDc1eWpWaktMcGNJWFdJcXBIK2J3OG1uQ0ZwQWRMeUNXRTkvVDZmQzVoSEg1UkI1cEJjdVNEMklEVFYvUjFMaEpzWVVlcThwS1U9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2FtcGFpbyIsImdpdmVuX25hbWUiOiJSZW5hbiIsImdyb3VwcyI6WyJlZGE4NTM4NC0wNmU0LTRlYjEtYTI1ZC0yOGNhYTYwNTA5YzEiLCI0NjlhZmZkZC1hZTQ4LTRiM2YtYTM4NS0yYmFjMWExYjQ5MzUiXSwiaXBhZGRyIjoiMTg5LjEwNi43OC4zNiIsIm5hbWUiOiJSZW5hbiBTYW1wYWlvIiwib2lkIjoiODllZTMyMWQtOTVhZS00ODdhLTlmZmQtYWUwNmU0MzRkMzY4IiwicHVpZCI6IjEwMDMyMDAxQTI5NTg3RTMiLCJyaCI6IjAuQVVVQS13U0hnZk9QS0UyYUJmVkN5UnEtUmtaSWYza0F1dGRQdWtQYXdmajJNQk5GQU1NLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjJXak1hTVFnQmlkZTY0LWQ3eFY0Wk1PNjdBOXJjR2I2RkpmRk00VDJSVUEiLCJ0aWQiOiI4MTg3MDRmYi04ZmYzLTRkMjgtOWEwNS1mNTQyYzkxYWJlNDYiLCJ1bmlxdWVfbmFtZSI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InJlbmFuc2FtcGFpb0BhbGV4YW5kZXJjb25jZWljYW9ldmxvczR1Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Ik9ERzROSERZSjBXRDdtMXp3aEYzQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjRhNWQ4ZjY1LTQxZGEtNGRlNC04OTY4LWUwMzViNjUzMzljZiIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfdGNkdCI6MTU3OTU3ODQ5NH0.IkAfG2ep0FybGVcgnCksqj7roWo-kRioM7Pt62Mx6A6boYuzI-eDMxfvZgsLIPLOfdz_fNOZnovipwty_sCXLL2agWqXgdpIuqTeU2-NtuXuzV7DddbQFDa3l9SrbMG7jOFEkXfKRjaNXCBYS0nIv-WBu7FB7UUK57gWFTqBzloBA2CPrbOixWfdyhzsmi74uLSw-LCubfH7uGlrBIhN80-APZJ5CgiERxZEtNeAqIDPj4qM8riesIncYRrFC-6TX-Kh6aGrPPovuBcwsfDV6a7N7XnJ3ej-cnCO5UlKY4x4x4IQYEoFmBuIKlcSEAr7PMNWqUbghqGQvgnoKyHs2Q" \
            https://management.azure.com/subscriptions/0b84aeb3-3723-42d4-b77a-6d8b2bb3353a/resources?api-version=2021-04-01

            git config user.email "renansampaio04@yahoo.com.br"
            git config user.name "RenanSampaioRS"

            git add response.json
            git commit -m "Adicionando arquivo com resposta da requisição GET"
            git push origin master
          fi

          # Verifica se houve adições e printa o resultado
          if [ "$added" != "[]" ]; then
            echo "Adições:"
            echo "$added"
          fi

          # Verifica se houve deleções e printa o resultado
          if [ "$deleted" != "[]" ]; then
            echo "Deleções:"
            echo "$deleted"
          fi

          if [[ -n "$added" ]]; then
            echo "Adições: $added"
          fi

          if [[ -n "$deleted" ]]; then
            echo "Deleções: $deleted"
          fi
