name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Release Notes        
        run: |       
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SECRET }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DevOps-Renan/devops_infrastructure_library/actions/variables/AZURE_RESOURCES_JSON \
            -d '{"name":"AZURE_RESOURCES_JSON","value":"octocatatt"}'

