name: Create Variable

on:
  workflow_dispatch:

jobs:
  create_variable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create variable
      run: |
        echo "MINHA_VARIAVEL=meu_valor" >> .env
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              
