name: Criar Variável de Ambiente
on: [push]

jobs:
  criar-variavel:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Release Notes        
        uses: actions/github-script@v6
        with:
          script: |       
            await github.request('POST /repos/{owner}/{repo}/actions/variables', {
              owner: 'DevOps-Renan',
              repo: 'devops_infrastructure_library',
              name: 'AZURE_RESOURCES_JSON1',
              value: 'ola',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
