name: Verificar expiração da PAT
on:
  push:
jobs:
  check-pat-expiration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Instalar dependências
        run: npm install @octokit/rest
      - name: Verificar expiração da PAT      
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require('@octokit/rest');

            const octokit = new Octokit({
              auth: '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'
            })

            await octokit.request('GET /organizations/{org}/personal-access-tokens', {
              org: 'DevOps-Renan',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })